(TeX-add-style-hook
 "FALL15-Notes"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-class-options
                     '(("memoir" "article" "oneside" "10pt")))
   (TeX-add-to-alist 'LaTeX-provided-package-options
                     '(("xcolor" "dvipsnames") ("enumitem" "inline")))
   (add-to-list 'LaTeX-verbatim-environments-local "lstlisting")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "lstinline")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "lstinline")
   (TeX-run-style-hooks
    "latex2e"
    "MA557/lectures/ma557-lecture-1"
    "MA557/lectures/ma557-lecture-2"
    "MA557/lectures/ma557-lecture-3"
    "MA557/lectures/ma557-lecture-4"
    "MA557/lectures/ma557-lecture-5"
    "MA557/lectures/ma557-lecture-6"
    "MA557/lectures/ma557-lecture-7"
    "MA557/lectures/ma557-lecture-8"
    "MA571/lectures/ma571-lecture-1"
    "MA571/lectures/ma571-lecture-2"
    "MA571/lectures/ma571-lecture-3"
    "MA571/lectures/ma571-lecture-4"
    "MA571/lectures/ma571-lecture-5"
    "MA571/lectures/ma571-lecture-6"
    "MA571/lectures/ma571-lecture-7"
    "MA571/lectures/ma571-lecture-8"
    "MA571/lectures/kaufmann-problems"
    "MA692-Wav/lectures/ma692-wav-lecture-1"
    "MA692-Wav/lectures/ma692-wav-lecture-2"
    "MA692-Wav/lectures/ma692-wav-lecture-3"
    "MA692-Wav/lectures/ma692-wav-lecture-4"
    "MA692-Wav/lectures/ma692-wav-lecture-5"
    "MA692-Wav/lectures/ma692-wav-lecture-6"
    "MA692-Wav/lectures/ma692-wav-lecture-7"
    "MA692-Wav/lectures/ma692-wav-lecture-8"
    "MA553/past-quals-compilation"
    "memoir"
    "memoir10"
    "geometry"
    "xcolor"
    "graphicx"
    "multicol"
    "enumitem"
    "listings"
    "mleftright"
    "microtype"
    "amsthm"
    "amssymb"
    "mathtools"
    "lualatex-math"
    "unicode-math")
   (TeX-add-symbols
    '("restr" 2)
    "id"
    "im"
    "GL"
    "GO"
    "OO"
    "SL"
    "SO"
    "CC"
    "CP"
    "GG"
    "NN"
    "PP"
    "QQ"
    "RP"
    "RR"
    "Sphere"
    "Torus"
    "ZZ"
    "documentauthor"
    "documenttitle"
    "coursename"
    "shorttitle"
    "documentsubject"
    "authoremail"
    "setminus"
    "phi"
    "epsilon")
   (LaTeX-add-environments
    '("problem" LaTeX-env-args ["argument"] 0)
    "theorem"
    "proposition"
    "corollary"
    "claim"
    "lemma"
    "axiom"
    "definition"
    "example"
    "examples"
    "exercise"
    "problem"
    "remark"
    "remarks"
    "observation"
    "observations")))

