# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Carlos's webpage
email: salinac@purdue.edu
# description: Welcome to my personal webpage.  Students, please check out my _teaching_ tab.
baseurl: ""
url: "https://math.purdue.edu/~salinac"
timezone: America/New_York

# Build settings
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
    enable_coderay: false
    auto_ids: true
    entity_output: symbolic
