name: Carlos Salinas
author: Carlos Salinas
url: http://math.purdue.edu/~salinac
base: ''
email: 'salinac@purdue.edu'

markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
    enable_coderay: false
    auto_ids: true
    entity_output: symbolic
highlighter: null

exclude:
    - bower_components
    - node_modules
    - package.json
    - bower.json
    - Makefile

permalink: /blog/:title.html

defaults:
    -
        scope:
            path: ""
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post

navigation:
    - title: home
      link: /
    - title: teaching
      link: /teaching.html
    - title: blog
      link: /blog/
    - title: contact
      link: /contact.html
